spring:
  application:
    name: taskmanager

  # Database configuration
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA configuration

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,logger,beans,mappings
        base-path: /actuator
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    description: A task management application built with Spring Boot.
    version: 1.0.0
    author: Hugo Lomba


# App info
app:
 name: Task Manager
 version: 1.0.0
 max-tasks-per-page: 10
